### ISSUE TITLE
Оновлення master

### ISSUE THREAD

**Issue by Palibrix** [Palibrix/projectZoo#10]
На гілці master додано файл Ticket, який відповідає за покупку квитків. Клас повністю функціональний та потребує деяких невеличких змін. При виклику кількості квитків після покупки, які залишились, показує точну кількість.
Клас написав: skxlpv
Під'єднав до інших класів: Palibrix

**Comment by sandriiy** [comment]
Назва класу завжди повинна відповідати якійсь одиниці, тобто: Білет, Людина, Машина, тощо... 
Заборонені назви: ПокупкаБілетів, Білети(множина), ОтриманняЛюдей, тощо...

Згідно до цієї проблеми:
- Клас Білет повинен повязувати дві одиниці: Людину та Шоу.
- Клас Білет повинен лише створюватись залежно від логіки в Зуу, а також не обмежуватись в кількості, це обмежує реалізацію та розширення класу, всі ці деталі повинні бути або в рамках Події або відсутні в принципі. Те саме відноситься до ціни, добре ціну зберігати як інформацію про білет, але вона не повинна сама визначати чи білет куплений чи ні.

**Comment by sandriiy** [comment]
@Palibrix

**Comment by sandriiy** [comment]
@skxlpv

**Comment by Palibrix** [comment]
Стосовно обмежень: кількість білетів йде як рандомне значення, яке генерується від 0 (тобто всі білети були продані ще до того, як покупець прийшов) до 10 (що можна з легкістю розширити у окремому класі). Це зроблено для того, щоб покупець не купляв безмежну кількість білетів, адже всюди є певна кількість місць, які можна купити. Тобто якщо білетів є 8, а людина купить 9, то їй видасть, що такої кількості у нас немає

**Comment by sandriiy** [comment]
@Palibrix Білети - представляють собою сутність яка у твоїй реалізації сама себе обмежує, кількість повинна визначатись або в Zoo або десь в рамках інших, но не в самому Білеті(х2).

**Comment by Palibrix** [comment]
У нас це так і зроблено. Кількість визначається у окремому класі, який передається у Zoo, клас Ticket не має до цього ніякого стосунку

**Comment by sandriiy** [comment]
На занятті обговоримо!
